import { createMuiTheme } from "@material-ui/core/styles";

export const theme = createMuiTheme({
  overrides: {
    MuiTypography: {
      h1: {
        fontFamily: "'Arial', sans-serif",
        fontSize: "41px",
        fontWeight: 600,
        fontStretch: "normal",
        fontStyle: "normal",
        lineHeight: 1.25,
        letterSpacing: "normal",
        color: "black",
      },
      h2: {
        fontFamily: "'Arial', sans-serif",
        fontSize: "31px",
        fontWeight: 600,
        fontStretch: "normal",
        fontStyle: "normal",
        lineHeight: 1.33,
        letterSpacing: "normal",
        color: "black",
      },
      h3: {
        fontFamily: "'Arial', sans-serif",
        fontSize: "25px",
        fontWeight: 600,
        fontStretch: "normal",
        fontStyle: "normal",
        lineHeight: 1.44,
        letterSpacing: "normal",
        color: "black",
      },
      h4: {
        fontFamily: "'Arial', sans-serif",
        fontSize: "20px",
        fontWeight: 500,
        fontStretch: "normal",
        fontStyle: "normal",
        lineHeight: 1.41,
        letterSpacing: "normal",
        color: "black",
      },
      h5: {
        fontFamily: "'Arial', sans-serif",
        fontSize: "18px",
        fontWeight: 500,
        fontStretch: "normal",
        fontStyle: "normal",
        lineHeight: 1.618,
        letterSpacing: "normal",
        color: "black",
      },
      caption: {
        fontFamily: "'Arial', sans-serif",
        fontSize: "31px",
        fontWeight: "normal",
        fontStretch: "normal",
        fontStyle: "normal",
        lineHeight: 1,
        letterSpacing: "normal",
        color: "black",
      },
      subtitle1: {
        fontFamily: "'Arial', sans-serif",
        fontSize: "16px",
        fontWeight: "normal",
        fontStretch: "normal",
        fontStyle: "normal",
        lineHeight: 1.69,
        letterSpacing: "normal",
        color: "black",
      },
      subtitle2: {
        fontFamily: "'Arial', sans-serif",
        fontSize: "13px",
        fontWeight: "normal",
        fontStretch: "normal",
        fontStyle: "normal",
        lineHeight: 1.43,
        letterSpacing: "normal",
        color: "black",
      },
    },
  },
});
